In [1]:
from pH_analysis import folderToArray
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
golgis = folderToArray("C:\\Users\\Peter\\Documents\\!Experiments\\test_phLIF_Tiff")

[[[ 104.  208.  208. ...   52.  156.   52.]
  [ 156.  208.  156. ...   52.  105.    0.]
  [ 104.  156.  208. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.   52.    0.]
  [   0.    0.    0. ...  104.   52.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[ 249.  698.  648. ...   99.   49.    0.]
  [ 149.   99.  448. ...   49.    0.   99.]
  [  99.  299.  399. ...   99.  150.   49.]
  ...
  [   0.    0.    0. ...   99.   49.    0.]
  [   0.    0.   49. ...    0.   49.   49.]
  [   0.    0.    0. ...   49.    0.    0.]]

 [[ 814.  800.  932. ... 1030.  814.  868.]
  [ 908.  815.  988. ...  912.  916.  749.]
  [1113. 1012. 1017. ... 1046.  993.  816.]
  ...
  [ 733.  953.  894. ...  786.  918. 1038.]
  [ 826.  667.  750. ...  974.  956.  816.]
  [ 776.  723.  796. ...  962.  946. 1008.]]]
[[[   0.   52.  157. ...   52.   52.   52.]
  [   0.   52.  156. ...   52.    0.    0.]
  [  52.  313.  417. ...   52.    0.    0.]
  ...
  [  52.  104.   52. ...   52.    0.    0.]
  

[[[   0.  104.   52. ...  156.  313.  952.]
  [  52.    0.  104. ...  626.  470.  679.]
  [   0.  104.  208. ... 1306. 1317.  574.]
  ...
  [ 313.  365.  365. ...  156.  313.  156.]
  [ 261.  900.  261. ...    0.   52.    0.]
  [ 156.  574.  365. ...    0.  104.    0.]]

 [[   0.   99.   49. ...  149.  349.  498.]
  [  49.   49.   49. ...  404.  604.  598.]
  [   0.   99.  149. ...  953.  753.  349.]
  ...
  [ 249.   49.  249. ...   49.  149.    0.]
  [ 399.  399.  299. ...    0.    0.  199.]
  [ 249.  349.  349. ...   49.    0.    0.]]

 [[ 911.  888.  772. ...  960.  889.  906.]
  [ 824.  934.  880. ...  790. 1016. 1206.]
  [ 882.  950.  916. ...  929. 1046. 1002.]
  ...
  [ 809.  860. 1024. ... 1064.  791.  987.]
  [ 951.  845. 1079. ...  920.  949.  968.]
  [1060.  969. 1296. ...  960.  913.  841.]]]
[[[ 156.  365.  945. 1306.  105.  371.  574.  470.  841.]
  [ 156.  679.  847.  783.  528.  208.  470.  417.  685.]
  [ 261.  731. 1102.  261.  261.  574.  626.  522.  626.]
  [ 319.  

[[[   0.    0.    0. ...   52.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.   52.    0. ...    0.   52.    0.]
  ...
  [  52.   52.  104. ...   52.    0.    0.]
  [ 104.  104.    0. ...    0.    0.    0.]
  [  52.    0.   52. ...   52.   52.    0.]]

 [[   0.   49.    0. ...   99.   49.    0.]
  [   0.    0.    0. ...    0.   49.   99.]
  [   0.    0.   49. ...    0.    0.   49.]
  ...
  [   0.    0.   49. ...    0.    0.   49.]
  [  99.   49.    0. ...    0.   99.    0.]
  [  99.  149.   99. ...    0.    0.   49.]]

 [[ 794.  850. 1014. ... 1071.  977. 1112.]
  [ 475.  709.  873. ...  715.  658.  787.]
  [ 478.  630. 1218. ...  854.  768.  773.]
  ...
  [ 382.  765. 1372. ...  863.  843.  956.]
  [ 998.  812.  903. ... 1106.  778.  710.]
  [ 934.  875.  890. ...  835.  904.  781.]]]
[[[   0.    0.    0. ...  104.   52.   52.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]
  ...
  [ 371.    0.   52. ...  110.  104.   52.]
  

[[[  52.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]
  [  52.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...   52.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[   0.    0.   49. ...    0.    0.    0.]
  [   0.   49.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.   49.]]

 [[ 527.  569.  794. ...  657.  900. 1015.]
  [ 671.  650.  879. ...  715.  868. 1027.]
  [ 847.  725.  590. ...  989.  888.  833.]
  ...
  [1023. 1274. 1264. ...  954.  850.  717.]
  [1351.  944. 1116. ...  874.  805.  852.]
  [1307.  957. 1143. ...  937. 1044. 1007.]]]
[[[   0.    0.    0. ...    0.    0.    0.]
  [ 104.    0.   52. ...    0.   52.    0.]
  [  52.   52.  104. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  

[[[  52.    0.    0. ...    0.   52.  104.]
  [   0.    0.  104. ...   52.   52.    0.]
  [  52.   52.   52. ...  104.   52.    0.]
  ...
  [ 104.  156.  104. ...  104.    0.   52.]
  [ 104.   52.    0. ...    0.    0.    0.]
  [   0.    0.  104. ...    0.    0.    0.]]

 [[  99.   49.   99. ...    0.   49.   49.]
  [  49.   49.   49. ...    0.    0.    0.]
  [ 149.  155.    0. ...    0.    0.    0.]
  ...
  [ 149.    0.  149. ...    0.   99.   99.]
  [   0.  149.   49. ...    0.   99.  149.]
  [  99.   49.   99. ...   49.    0.   49.]]

 [[ 987.  562.  511. ...  837. 1151.  922.]
  [ 628.  482.  616. ...  851.  827.  749.]
  [ 404.  542.  734. ...  889.  623.  777.]
  ...
  [1127.  843.  922. ... 1003. 1017.  805.]
  [1128.  928.  903. ...  753.  710.  591.]
  [1055.  768. 1095. ...  971.  759.  802.]]]
[[[   0.   52.   52. ...    0.   52.    0.]
  [   0.    0.    0. ...   52.    0.    0.]
  [   0.   52.    0. ...  104.   52.   52.]
  ...
  [ 156.    0.    0. ...   52.    0.    0.]
  

[[[ 52.   0.  52. ...  52. 104. 104.]
  [  0.  52.  52. ...  52.   0. 156.]
  [ 52. 104.  52. ... 104. 208. 313.]
  ...
  [  0. 156. 210. ... 104.  52.   0.]
  [105. 104. 156. ...  52.   0.   0.]
  [156. 104.  52. ...  52.   0.   0.]]

 [[ 49.  49.   0. ...  99.  49.  49.]
  [ 49.  49.  49. ... 199.  50. 199.]
  [ 49.   0.  49. ... 250.  49. 249.]
  ...
  [ 99. 149.  49. ...   0.  49.   0.]
  [  0. 199. 199. ...  49.   0.   0.]
  [  0.  50. 149. ...  99.  99.  49.]]

 [[936. 722. 711. ... 743. 714. 542.]
  [671. 621. 759. ... 836. 826. 617.]
  [551. 634. 625. ... 656. 770. 680.]
  ...
  [574. 709. 827. ... 228. 296. 409.]
  [576. 972. 909. ... 362. 493. 735.]
  [695. 616. 862. ... 682. 626. 631.]]]
[[[  52.    0.    0. ...    0.    0.   52.]
  [   0.    0.  156. ...    0.   52.    0.]
  [  52.    0.  104. ...    0.    0.    0.]
  ...
  [  52.    0.   52. ...    0.    0.   52.]
  [   0.    0.    0. ...  104.  104.  104.]
  [   0.    0.   52. ...   52.   52.   52.]]

 [[   0.    0.  199.

[[[  0.   0.   0. ...  52.   0.   0.]
  [  0.  52.   0. ... 104.  52.   0.]
  [  0.   0.   0. ...  52.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  52.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.  49.   0. ...   0.  49.  49.]
  [ 49.   0.   0. ...  49.  99.   0.]
  [  0.   0.   0. ...  49.   0.  49.]
  ...
  [  0.   0.  99. ...  49.   0.  49.]
  [ 49.   0.   0. ...   0.   0.  49.]
  [ 49.   0.   0. ...   0.   0.   0.]]

 [[686. 653. 693. ... 323. 371. 581.]
  [648. 499. 712. ... 302. 326. 569.]
  [685. 564. 561. ... 500. 569. 457.]
  ...
  [695. 810. 887. ... 459. 632. 934.]
  [575. 686. 693. ... 572. 631. 705.]
  [570. 774. 843. ... 580. 763. 653.]]]
[[[ 52.  52.   0. ...   0.  52.   0.]
  [104.   0.   0. ...   0.   0.  52.]
  [  0. 104.   0. ...   0.   0. 156.]
  ...
  [ 52. 313. 104. ...   0.   0.   0.]
  [ 52.  52. 104. ...  52.   0.   0.]
  [  0.   0.   0. ...  52.   0.   0.]]

 [[ 49. 149.   0. ...  49.  49. 149.]
  [  0.   0. 149. 

[[[  0.   0.   0. ...  52.  52.   0.]
  [ 52.   0.   0. ... 104.  52.   0.]
  [  0.   0.   0. ...   0. 104.   0.]
  ...
  [  0.   0.   0. ...   0.  52.  52.]
  [  0.   0.   0. ...  52.   0.  52.]
  [  0.   0.   0. ...  52.   0.  52.]]

 [[  0.   0.   0. ...  49.   0.   0.]
  [  0.   0. 100. ...   0.  49. 149.]
  [  0.  49.  99. ...  49.  99.  99.]
  ...
  [  0.   0.   0. ...   0.  49.  49.]
  [  0.   0.   0. ...   0.  49.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[582. 702. 548. ... 634. 515. 577.]
  [725. 601. 626. ... 598. 571. 684.]
  [769. 748. 819. ... 619. 788. 834.]
  ...
  [765. 776. 738. ... 542. 614. 865.]
  [858. 855. 840. ... 594. 541. 654.]
  [664. 762. 633. ... 658. 669. 577.]]]
[[[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [ 52.   0.   0. ...   0.  52.   0.]
  [104.   0. 208. ...  52.  52.  52.]
  [ 52. 104.   0. ...   0. 156.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. 

[[[ 156.  104.  104. ...  104.   52.  104.]
  [ 156.  208.   52. ...   52.  156.   52.]
  [ 104.  208.  156. ...    0.    0.  104.]
  ...
  [   0.    0.    0. ...  156.  104.    0.]
  [   0.    0.    0. ...  156.    0.  104.]
  [   0.    0.    0. ...   52.   52.   52.]]

 [[  99.   49.    0. ...    0.    0.    0.]
  [   0.  199.  149. ...    0.  149.  149.]
  [  49.   99.   99. ...  149.   49.    0.]
  ...
  [   0.    0.    0. ...  149.  149.   49.]
  [   0.    0.    0. ...  149.   99.   49.]
  [   0.    0.    0. ...  149.  199.   99.]]

 [[ 639. 1039.  771. ...  703.  835.  636.]
  [ 601.  731.  652. ...  819.  789.  574.]
  [ 785.  673.  699. ...  724.  807.  838.]
  ...
  [ 933.  673.  747. ...  991.  839. 1048.]
  [ 947.  760.  876. ... 1188.  549. 1031.]
  [ 719.  908.  902. ...  970.  547.  833.]]]
[[[   0.   52.    0. ...    0.   52.    0.]
  [  52.  104.    0. ...    0.    0.    0.]
  [  52.    0.    0. ...    0.    0.    0.]
  ...
  [   0.   52.    0. ...    0.    0.    0.]
  

[[[   0.  104.    0. ...    0.   52.    0.]
  [ 104.    0.   52. ...   52.  104.   52.]
  [   0.   52.    0. ...  104.   52.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]]

 [[   0.    0.   99. ...   49.    0.   49.]
  [   0.   49.    0. ...   99.    0.    0.]
  [  99.    0.   49. ...   99.    0.   99.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[ 739.  735.  693. ...  970. 1184.  828.]
  [ 802.  980.  785. ...  841.  890.  992.]
  [ 887.  706.  732. ...  990.  675.  793.]
  ...
  [ 892.  788.  622. ...  875.  723.  786.]
  [ 669.  822.  841. ...  819.  738.  876.]
  [ 988.  756.  947. ...  886.  890.  848.]]]
[[[   0.   52.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.   52.    0.]
  ...
  [  52.    0.    0. ...    0.    0.    0.]
  

[[[   0.    0.    0. ...   52.  156.  104.]
  [   0.    0.   52. ...  156.   52.  156.]
  [  52.   52.    0. ...   52.    0.  156.]
  ...
  [  52.    0.  104. ...    0.  104.    0.]
  [ 156.  104.    0. ...   52.    0.    0.]
  [ 104.   52.    0. ...   52.    0.    0.]]

 [[   0.    0.    0. ...  199.   99.    0.]
  [   0.    0.   99. ...   99.    0.   99.]
  [   0.   49.    0. ...   49.   49.   99.]
  ...
  [   0.    0.   49. ...    0.    0.    0.]
  [   0.   49.    0. ...    0.   49.    0.]
  [  99.    0.   49. ...    0.    0.    0.]]

 [[ 901.  710.  806. ... 1077. 1006.  884.]
  [ 918.  722.  954. ...  678.  849.  870.]
  [1002.  890.  833. ... 1023.  754.  708.]
  ...
  [1149.  998. 1121. ... 1172.  968.  916.]
  [ 955.  958. 1086. ...  915.  947.  992.]
  [1091.  955. 1116. ... 1172. 1093. 1030.]]]
[[[  52.  104.  104. ...    0.   52.  104.]
  [ 104.    0.  156. ...    0.   52.   52.]
  [   0.   52.    0. ...  104.   52.    0.]
  ...
  [   0.    0.   52. ...   52.  104.   52.]
  

[[[   0.    0.  104. ...    0.    0.    0.]
  [   0.   52.    0. ...    0.    0.    0.]
  [   0.   52.    0. ...    0.    0.    0.]
  ...
  [ 313.  156.  313. ...    0.  261.  104.]
  [ 104.  156.  104. ...  104.   52.  261.]
  [ 208.  156.   52. ...  208.  208.   52.]]

 [[   0.    0.   49. ...    0.    0.    0.]
  [  49.    0.    0. ...    0.    0.    0.]
  [  49.    0.    0. ...    0.    0.    0.]
  ...
  [  99.   99.   99. ...   99.   49.   99.]
  [  49.   99.   49. ...    0.   99.   49.]
  [   0.   49.    0. ...   49.   99.   99.]]

 [[ 789.  854.  730. ...  961.  892. 1018.]
  [ 984.  631.  715. ...  755.  840.  677.]
  [ 830.  809.  760. ...  716.  611.  735.]
  ...
  [ 790.  809.  849. ...  922. 1019.  790.]
  [ 758.  766.  785. ...  894.  951.  960.]
  [1008.  899.  822. ...  671.  887. 1089.]]]
[[[   0.    0.   52. ...   52.    0.  156.]
  [   0.    0.   52. ...    0.    0.    0.]
  [   0.   52.   52. ...  156.  313.   52.]
  ...
  [ 522.  731.  894. ...    0.   52.   52.]
  

[[[   0.   52.   52. ...    0.    0.    0.]
  [ 104.   52.  104. ...   52.    0.    0.]
  [ 104.  105.  156. ...   52.   52.   52.]
  ...
  [ 261.   52.  156. ...   52.    0.    0.]
  [  52.  208.  208. ...  104.   52.   52.]
  [ 208.  104.   52. ...    0.  105.  156.]]

 [[   0.    0.    0. ...   49.    0.    0.]
  [   0.   49.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.   49.    0.]
  ...
  [   0.    0.   99. ...   49.    0.    0.]
  [  49.    0.    0. ...   50.   49.   49.]
  [  49.  100.   49. ...   50.   49.   49.]]

 [[1254.  875.  879. ... 1027. 1208. 1092.]
  [ 969.  988.  804. ... 1076. 1028. 1308.]
  [ 926.  886.  802. ...  965. 1147. 1362.]
  ...
  [ 877.  720.  888. ...  764.  728.  758.]
  [ 987. 1080.  982. ...  775.  988. 1109.]
  [ 729.  821. 1020. ...  907.  902.  893.]]]
[[[ 104.    0.    0. ...  208.  208.  261.]
  [  52.    0.    0. ...  313.  313.  417.]
  [   0.    0.   52. ...  261.  470.  470.]
  ...
  [  52.  104.   52. ...    0.  104.   52.]
  

[[[ 52.  52.  52. ...   0.  52.  52.]
  [  0.  52.   0. ... 105. 210. 104.]
  [ 52. 156. 104. ...   0.  52.   0.]
  ...
  [208. 319. 522. ...  52.  52. 104.]
  [ 52. 208. 156. ...  52. 156.  52.]
  [ 52.   0.   0. ... 208.   0. 156.]]

 [[100.  99.  49. ...   0.  99. 249.]
  [  0.   0.   0. ... 299.  99. 100.]
  [  0.  99.  50. ... 199. 155.  99.]
  ...
  [  0.  49.   0. ...  50. 149. 299.]
  [ 49.   0.   0. ... 249.  99. 199.]
  [  0.   0.  49. ... 349.  99.   0.]]

 [[716. 685. 815. ... 734. 880. 728.]
  [594. 838. 831. ... 820. 597. 707.]
  [737. 740. 651. ... 942. 814. 738.]
  ...
  [712. 954. 897. ... 904. 709. 749.]
  [927. 752. 721. ... 783. 800. 963.]
  [864. 785. 669. ... 889. 767. 823.]]]
[[[ 156.  104.    0. ...    0.    0.    0.]
  [  52.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...   52.   52.   52.]
  [   0.    0.    0. ...  104.   52.   52.]
  [   0.    0.    0. ...  156.  208.    0.]]

 [[   0.    0.    0.

In [4]:
for item in golgis:
    print(item.name + "\n" + item.group)
   # print(item.data[0])

B4GALT1_unt_001_cell_1
B4GALT1
B4GALT1_unt_001_cell_2
B4GALT1
B4GALT1_unt_001_cell_3
B4GALT1
B4GALT1_unt_001_cell_4
B4GALT1
B4GALT1_unt_001_cell_5
B4GALT1
B4GALT1_unt_001_cell_6
B4GALT1
B4GALT1_unt_001_cell_7
B4GALT1
B4GALT1_unt_001_cell_8
B4GALT1
B4GALT1_unt_001_cell_9
B4GALT1
B4GALT1_unt_001_cell_10
B4GALT1
B4GALT1_unt_001_cell_11
B4GALT1
B4GALT1_unt_001_cell_12
B4GALT1
B4GALT1_unt_001_cell_13
B4GALT1
B4GALT1_unt_001_cell_14
B4GALT1
B4GALT1_unt_001_cell_15
B4GALT1
B4GALT1_unt_001_cell_16
B4GALT1
MGAT2_pH35_002_cell_1
pH3.5
MGAT2_pH35_002_cell_2
pH3.5
MGAT2_pH35_002_cell_3
pH3.5
MGAT2_pH35_002_cell_4
pH3.5
MGAT2_pH35_002_cell_5
pH3.5
MGAT2_pH35_002_cell_6
pH3.5
MGAT2_pH35_002_cell_7
pH3.5
MGAT2_pH35_002_cell_8
pH3.5
MGAT2_pH35_002_cell_9
pH3.5
MGAT2_pH35_002_cell_10
pH3.5
MGAT2_pH35_002_cell_11
pH3.5
MGAT2_pH35_002_cell_12
pH3.5
MGAT2_pH35_002_cell_13
pH3.5
MGAT2_pH40_003_cell_1
pH4.0
MGAT2_pH40_003_cell_2
pH4.0
MGAT2_pH40_003_cell_3
pH4.0
MGAT2_pH40_003_cell_4
pH4.0
MGAT2_pH40_003_ce

In [112]:
df =pd.DataFrame([g.toDataframe() for g in golgis])

In [2]:
from segmentation import loadImage, makeContours, evaluateGolgi

In [3]:
df, name = loadImage("test_img/MGAT2_test1.tif")
contours, thresh = makeContours(df)
golgis = evaluateGolgi(df, contours, thresh, name)

[[[  0. 104.  52. ...   0.   0.   0.]
  [104.   0. 104. ...   0.  52.  52.]
  [ 52.  52. 104. ... 104.   0.  52.]
  ...
  [156.   0. 208. ...  52.   0.   0.]
  [ 52. 261. 574. ...   0. 104.   0.]
  [156. 261. 208. ...   0.   0.  52.]]

 [[149.   0.  49. ...   0.   0.   0.]
  [  0.  49.  49. ...   0.  49.  99.]
  [ 49.   0.  49. ...   0.   0.  49.]
  ...
  [ 49.   0.  99. ...   0.   0.   0.]
  [  0.  99.   0. ...   0.   0.   0.]
  [ 49. 149.   0. ...  49.  49.   0.]]

 [[873. 765. 704. ... 876. 808. 829.]
  [815. 727. 724. ... 868. 913. 764.]
  [956. 691. 575. ... 833. 779. 801.]
  ...
  [714. 890. 739. ... 833. 849. 931.]
  [684. 884. 795. ... 740. 776. 731.]
  [835. 807. 877. ... 769. 903. 960.]]]
Good Golgi? Y/N n
[[[  52.  156.   52.   52.    0.   52.  313.  365.  313.  104.   52.
    522.  417.]
  [ 156.  261.  208.  313.  313.   52.  261.  522.   52.  208.  261.
    417.  417.]
  [ 156.  208.  208.  261.  365.  313.  208.  208.  365.  313.  313.
    156.  319.]
  [ 156.  104.  156

Good Golgi? Y/N y
[[[104. 104. 104. ...   0.  52.   0.]
  [ 52.   0.  52. ...   0.   0.  52.]
  [ 52.  52.  52. ...   0.   0.  52.]
  ...
  [  0.   0.   0. ...  52. 210.  52.]
  [ 52.  52.  52. ...  52. 104. 156.]
  [  0.   0.  52. ...   0.   0.  52.]]

 [[  0.   0.   0. ...   0.  50.   0.]
  [  0.  49.   0. ...  49.   0.  49.]
  [ 49.   0.   0. ...  50.   0.  49.]
  ...
  [ 49.   0.   0. ...   0.   0. 149.]
  [  0.   0.   0. ...   0.  49.  50.]
  [  0.   0.   0. ...   0.   0.  49.]]

 [[727. 896. 934. ... 816. 909. 940.]
  [820. 770. 877. ... 816. 836. 825.]
  [869. 949. 870. ... 788. 775. 883.]
  ...
  [863. 799. 848. ... 685. 784. 766.]
  [697. 848. 805. ... 672. 797. 590.]
  [905. 764. 766. ... 884. 860. 835.]]]
Good Golgi? Y/N y
[[[   0.  104.   52. ...  104.    0.    0.]
  [   0.    0.  104. ...   52.    0.   52.]
  [  52.   52.   52. ...    0.   52.    0.]
  ...
  [   0.    0.    0. ...   52.    0.   52.]
  [   0.    0.    0. ...   52.    0.    0.]
  [   0.    0.    0. ...    0.

In [4]:
golgis

In [5]:
for item in golgis:
    item.calcRatio(0, 1)
    #print(item.data)
    print(item.ratio)

1.3260400707839195
1.5260612922022379
1.2609334061107431
1.8062124162641704
1.5423162612448789
1.503555510793101
1.401871401771681
1.4180358058217057
1.4213001759645336
1.6068088517780186
1.1087991108029214
1.8999468269098312
1.7611558778376881
2.206691663609071
1.6123324602282094
1.4385485868260208
0.921279560868173
0.9179367924970783
0.9381400090331097
0.9787768336910966
0.8975989289241394
1.0365055770684177
1.041338679422923
1.05105767189082
1.0148268880963311
1.1858677575262078
1.0742911812330005
1.0735449156632388
1.0177975454840367
1.2778800610615317
1.3293020070974655
1.2834138695596398
1.201825046759515
1.405998709601133
1.2634580451091972
1.2999234805926714
1.080352814174721
1.388205415208417
0.5252525252525253
1.4680465968040954
0.9875166819769768
1.074517844952202
0.94382247498721
0.915871817235887
1.049769461763221
1.0802083250083587
1.0822590138025552
1.1122997016829421
1.0338975324267239
1.154835401234439
1.0226953487502135
1.0888277595344797
0.9492408284281696
1.13140840

In [3]:
golgis = folderToArray("C:\\Users\\Peter\\Documents\\!Experiments\\test_phLIF_Tiff")

[[[ 104.  208.  208. ...   52.  156.   52.]
  [ 156.  208.  156. ...   52.  105.    0.]
  [ 104.  156.  208. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.   52.    0.]
  [   0.    0.    0. ...  104.   52.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[ 249.  698.  648. ...   99.   49.    0.]
  [ 149.   99.  448. ...   49.    0.   99.]
  [  99.  299.  399. ...   99.  150.   49.]
  ...
  [   0.    0.    0. ...   99.   49.    0.]
  [   0.    0.   49. ...    0.   49.   49.]
  [   0.    0.    0. ...   49.    0.    0.]]

 [[ 814.  800.  932. ... 1030.  814.  868.]
  [ 908.  815.  988. ...  912.  916.  749.]
  [1113. 1012. 1017. ... 1046.  993.  816.]
  ...
  [ 733.  953.  894. ...  786.  918. 1038.]
  [ 826.  667.  750. ...  974.  956.  816.]
  [ 776.  723.  796. ...  962.  946. 1008.]]]
[[[   0.   52.  157. ...   52.   52.   52.]
  [   0.   52.  156. ...   52.    0.    0.]
  [  52.  313.  417. ...   52.    0.    0.]
  ...
  [  52.  104.   52. ...   52.    0.    0.]
  

[[[   0.  104.   52. ...  156.  313.  952.]
  [  52.    0.  104. ...  626.  470.  679.]
  [   0.  104.  208. ... 1306. 1317.  574.]
  ...
  [ 313.  365.  365. ...  156.  313.  156.]
  [ 261.  900.  261. ...    0.   52.    0.]
  [ 156.  574.  365. ...    0.  104.    0.]]

 [[   0.   99.   49. ...  149.  349.  498.]
  [  49.   49.   49. ...  404.  604.  598.]
  [   0.   99.  149. ...  953.  753.  349.]
  ...
  [ 249.   49.  249. ...   49.  149.    0.]
  [ 399.  399.  299. ...    0.    0.  199.]
  [ 249.  349.  349. ...   49.    0.    0.]]

 [[ 911.  888.  772. ...  960.  889.  906.]
  [ 824.  934.  880. ...  790. 1016. 1206.]
  [ 882.  950.  916. ...  929. 1046. 1002.]
  ...
  [ 809.  860. 1024. ... 1064.  791.  987.]
  [ 951.  845. 1079. ...  920.  949.  968.]
  [1060.  969. 1296. ...  960.  913.  841.]]]
[[[ 156.  365.  945. 1306.  105.  371.  574.  470.  841.]
  [ 156.  679.  847.  783.  528.  208.  470.  417.  685.]
  [ 261.  731. 1102.  261.  261.  574.  626.  522.  626.]
  [ 319.  

[[[   0.    0.    0. ...   52.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.   52.    0. ...    0.   52.    0.]
  ...
  [  52.   52.  104. ...   52.    0.    0.]
  [ 104.  104.    0. ...    0.    0.    0.]
  [  52.    0.   52. ...   52.   52.    0.]]

 [[   0.   49.    0. ...   99.   49.    0.]
  [   0.    0.    0. ...    0.   49.   99.]
  [   0.    0.   49. ...    0.    0.   49.]
  ...
  [   0.    0.   49. ...    0.    0.   49.]
  [  99.   49.    0. ...    0.   99.    0.]
  [  99.  149.   99. ...    0.    0.   49.]]

 [[ 794.  850. 1014. ... 1071.  977. 1112.]
  [ 475.  709.  873. ...  715.  658.  787.]
  [ 478.  630. 1218. ...  854.  768.  773.]
  ...
  [ 382.  765. 1372. ...  863.  843.  956.]
  [ 998.  812.  903. ... 1106.  778.  710.]
  [ 934.  875.  890. ...  835.  904.  781.]]]
[[[   0.    0.    0. ...  104.   52.   52.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]
  ...
  [ 371.    0.   52. ...  110.  104.   52.]
  

[[[  52.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]
  [  52.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...   52.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[   0.    0.   49. ...    0.    0.    0.]
  [   0.   49.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.   49.]]

 [[ 527.  569.  794. ...  657.  900. 1015.]
  [ 671.  650.  879. ...  715.  868. 1027.]
  [ 847.  725.  590. ...  989.  888.  833.]
  ...
  [1023. 1274. 1264. ...  954.  850.  717.]
  [1351.  944. 1116. ...  874.  805.  852.]
  [1307.  957. 1143. ...  937. 1044. 1007.]]]
[[[   0.    0.    0. ...    0.    0.    0.]
  [ 104.    0.   52. ...    0.   52.    0.]
  [  52.   52.  104. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  

[[[  52.    0.    0. ...    0.   52.  104.]
  [   0.    0.  104. ...   52.   52.    0.]
  [  52.   52.   52. ...  104.   52.    0.]
  ...
  [ 104.  156.  104. ...  104.    0.   52.]
  [ 104.   52.    0. ...    0.    0.    0.]
  [   0.    0.  104. ...    0.    0.    0.]]

 [[  99.   49.   99. ...    0.   49.   49.]
  [  49.   49.   49. ...    0.    0.    0.]
  [ 149.  155.    0. ...    0.    0.    0.]
  ...
  [ 149.    0.  149. ...    0.   99.   99.]
  [   0.  149.   49. ...    0.   99.  149.]
  [  99.   49.   99. ...   49.    0.   49.]]

 [[ 987.  562.  511. ...  837. 1151.  922.]
  [ 628.  482.  616. ...  851.  827.  749.]
  [ 404.  542.  734. ...  889.  623.  777.]
  ...
  [1127.  843.  922. ... 1003. 1017.  805.]
  [1128.  928.  903. ...  753.  710.  591.]
  [1055.  768. 1095. ...  971.  759.  802.]]]
[[[   0.   52.   52. ...    0.   52.    0.]
  [   0.    0.    0. ...   52.    0.    0.]
  [   0.   52.    0. ...  104.   52.   52.]
  ...
  [ 156.    0.    0. ...   52.    0.    0.]
  

[[[ 52.   0.  52. ...  52. 104. 104.]
  [  0.  52.  52. ...  52.   0. 156.]
  [ 52. 104.  52. ... 104. 208. 313.]
  ...
  [  0. 156. 210. ... 104.  52.   0.]
  [105. 104. 156. ...  52.   0.   0.]
  [156. 104.  52. ...  52.   0.   0.]]

 [[ 49.  49.   0. ...  99.  49.  49.]
  [ 49.  49.  49. ... 199.  50. 199.]
  [ 49.   0.  49. ... 250.  49. 249.]
  ...
  [ 99. 149.  49. ...   0.  49.   0.]
  [  0. 199. 199. ...  49.   0.   0.]
  [  0.  50. 149. ...  99.  99.  49.]]

 [[936. 722. 711. ... 743. 714. 542.]
  [671. 621. 759. ... 836. 826. 617.]
  [551. 634. 625. ... 656. 770. 680.]
  ...
  [574. 709. 827. ... 228. 296. 409.]
  [576. 972. 909. ... 362. 493. 735.]
  [695. 616. 862. ... 682. 626. 631.]]]
[[[  52.    0.    0. ...    0.    0.   52.]
  [   0.    0.  156. ...    0.   52.    0.]
  [  52.    0.  104. ...    0.    0.    0.]
  ...
  [  52.    0.   52. ...    0.    0.   52.]
  [   0.    0.    0. ...  104.  104.  104.]
  [   0.    0.   52. ...   52.   52.   52.]]

 [[   0.    0.  199.

[[[  0.   0.   0. ...  52.   0.   0.]
  [  0.  52.   0. ... 104.  52.   0.]
  [  0.   0.   0. ...  52.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...  52.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[  0.  49.   0. ...   0.  49.  49.]
  [ 49.   0.   0. ...  49.  99.   0.]
  [  0.   0.   0. ...  49.   0.  49.]
  ...
  [  0.   0.  99. ...  49.   0.  49.]
  [ 49.   0.   0. ...   0.   0.  49.]
  [ 49.   0.   0. ...   0.   0.   0.]]

 [[686. 653. 693. ... 323. 371. 581.]
  [648. 499. 712. ... 302. 326. 569.]
  [685. 564. 561. ... 500. 569. 457.]
  ...
  [695. 810. 887. ... 459. 632. 934.]
  [575. 686. 693. ... 572. 631. 705.]
  [570. 774. 843. ... 580. 763. 653.]]]
[[[ 52.  52.   0. ...   0.  52.   0.]
  [104.   0.   0. ...   0.   0.  52.]
  [  0. 104.   0. ...   0.   0. 156.]
  ...
  [ 52. 313. 104. ...   0.   0.   0.]
  [ 52.  52. 104. ...  52.   0.   0.]
  [  0.   0.   0. ...  52.   0.   0.]]

 [[ 49. 149.   0. ...  49.  49. 149.]
  [  0.   0. 149. 

[[[  0.   0.   0. ...  52.  52.   0.]
  [ 52.   0.   0. ... 104.  52.   0.]
  [  0.   0.   0. ...   0. 104.   0.]
  ...
  [  0.   0.   0. ...   0.  52.  52.]
  [  0.   0.   0. ...  52.   0.  52.]
  [  0.   0.   0. ...  52.   0.  52.]]

 [[  0.   0.   0. ...  49.   0.   0.]
  [  0.   0. 100. ...   0.  49. 149.]
  [  0.  49.  99. ...  49.  99.  99.]
  ...
  [  0.   0.   0. ...   0.  49.  49.]
  [  0.   0.   0. ...   0.  49.   0.]
  [  0.   0.   0. ...   0.   0.   0.]]

 [[582. 702. 548. ... 634. 515. 577.]
  [725. 601. 626. ... 598. 571. 684.]
  [769. 748. 819. ... 619. 788. 834.]
  ...
  [765. 776. 738. ... 542. 614. 865.]
  [858. 855. 840. ... 594. 541. 654.]
  [664. 762. 633. ... 658. 669. 577.]]]
[[[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  ...
  [ 52.   0.   0. ...   0.  52.   0.]
  [104.   0. 208. ...  52.  52.  52.]
  [ 52. 104.   0. ...   0. 156.   0.]]

 [[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. 

[[[ 156.  104.  104. ...  104.   52.  104.]
  [ 156.  208.   52. ...   52.  156.   52.]
  [ 104.  208.  156. ...    0.    0.  104.]
  ...
  [   0.    0.    0. ...  156.  104.    0.]
  [   0.    0.    0. ...  156.    0.  104.]
  [   0.    0.    0. ...   52.   52.   52.]]

 [[  99.   49.    0. ...    0.    0.    0.]
  [   0.  199.  149. ...    0.  149.  149.]
  [  49.   99.   99. ...  149.   49.    0.]
  ...
  [   0.    0.    0. ...  149.  149.   49.]
  [   0.    0.    0. ...  149.   99.   49.]
  [   0.    0.    0. ...  149.  199.   99.]]

 [[ 639. 1039.  771. ...  703.  835.  636.]
  [ 601.  731.  652. ...  819.  789.  574.]
  [ 785.  673.  699. ...  724.  807.  838.]
  ...
  [ 933.  673.  747. ...  991.  839. 1048.]
  [ 947.  760.  876. ... 1188.  549. 1031.]
  [ 719.  908.  902. ...  970.  547.  833.]]]
[[[   0.   52.    0. ...    0.   52.    0.]
  [  52.  104.    0. ...    0.    0.    0.]
  [  52.    0.    0. ...    0.    0.    0.]
  ...
  [   0.   52.    0. ...    0.    0.    0.]
  

[[[   0.  104.    0. ...    0.   52.    0.]
  [ 104.    0.   52. ...   52.  104.   52.]
  [   0.   52.    0. ...  104.   52.    0.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]]

 [[   0.    0.   99. ...   49.    0.   49.]
  [   0.   49.    0. ...   99.    0.    0.]
  [  99.    0.   49. ...   99.    0.   99.]
  ...
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]]

 [[ 739.  735.  693. ...  970. 1184.  828.]
  [ 802.  980.  785. ...  841.  890.  992.]
  [ 887.  706.  732. ...  990.  675.  793.]
  ...
  [ 892.  788.  622. ...  875.  723.  786.]
  [ 669.  822.  841. ...  819.  738.  876.]
  [ 988.  756.  947. ...  886.  890.  848.]]]
[[[   0.   52.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.   52.    0.]
  ...
  [  52.    0.    0. ...    0.    0.    0.]
  

[[[   0.    0.    0. ...   52.  156.  104.]
  [   0.    0.   52. ...  156.   52.  156.]
  [  52.   52.    0. ...   52.    0.  156.]
  ...
  [  52.    0.  104. ...    0.  104.    0.]
  [ 156.  104.    0. ...   52.    0.    0.]
  [ 104.   52.    0. ...   52.    0.    0.]]

 [[   0.    0.    0. ...  199.   99.    0.]
  [   0.    0.   99. ...   99.    0.   99.]
  [   0.   49.    0. ...   49.   49.   99.]
  ...
  [   0.    0.   49. ...    0.    0.    0.]
  [   0.   49.    0. ...    0.   49.    0.]
  [  99.    0.   49. ...    0.    0.    0.]]

 [[ 901.  710.  806. ... 1077. 1006.  884.]
  [ 918.  722.  954. ...  678.  849.  870.]
  [1002.  890.  833. ... 1023.  754.  708.]
  ...
  [1149.  998. 1121. ... 1172.  968.  916.]
  [ 955.  958. 1086. ...  915.  947.  992.]
  [1091.  955. 1116. ... 1172. 1093. 1030.]]]
[[[  52.  104.  104. ...    0.   52.  104.]
  [ 104.    0.  156. ...    0.   52.   52.]
  [   0.   52.    0. ...  104.   52.    0.]
  ...
  [   0.    0.   52. ...   52.  104.   52.]
  

[[[   0.    0.  104. ...    0.    0.    0.]
  [   0.   52.    0. ...    0.    0.    0.]
  [   0.   52.    0. ...    0.    0.    0.]
  ...
  [ 313.  156.  313. ...    0.  261.  104.]
  [ 104.  156.  104. ...  104.   52.  261.]
  [ 208.  156.   52. ...  208.  208.   52.]]

 [[   0.    0.   49. ...    0.    0.    0.]
  [  49.    0.    0. ...    0.    0.    0.]
  [  49.    0.    0. ...    0.    0.    0.]
  ...
  [  99.   99.   99. ...   99.   49.   99.]
  [  49.   99.   49. ...    0.   99.   49.]
  [   0.   49.    0. ...   49.   99.   99.]]

 [[ 789.  854.  730. ...  961.  892. 1018.]
  [ 984.  631.  715. ...  755.  840.  677.]
  [ 830.  809.  760. ...  716.  611.  735.]
  ...
  [ 790.  809.  849. ...  922. 1019.  790.]
  [ 758.  766.  785. ...  894.  951.  960.]
  [1008.  899.  822. ...  671.  887. 1089.]]]
[[[   0.    0.   52. ...   52.    0.  156.]
  [   0.    0.   52. ...    0.    0.    0.]
  [   0.   52.   52. ...  156.  313.   52.]
  ...
  [ 522.  731.  894. ...    0.   52.   52.]
  

[[[   0.   52.   52. ...    0.    0.    0.]
  [ 104.   52.  104. ...   52.    0.    0.]
  [ 104.  105.  156. ...   52.   52.   52.]
  ...
  [ 261.   52.  156. ...   52.    0.    0.]
  [  52.  208.  208. ...  104.   52.   52.]
  [ 208.  104.   52. ...    0.  105.  156.]]

 [[   0.    0.    0. ...   49.    0.    0.]
  [   0.   49.    0. ...    0.    0.    0.]
  [   0.    0.    0. ...    0.   49.    0.]
  ...
  [   0.    0.   99. ...   49.    0.    0.]
  [  49.    0.    0. ...   50.   49.   49.]
  [  49.  100.   49. ...   50.   49.   49.]]

 [[1254.  875.  879. ... 1027. 1208. 1092.]
  [ 969.  988.  804. ... 1076. 1028. 1308.]
  [ 926.  886.  802. ...  965. 1147. 1362.]
  ...
  [ 877.  720.  888. ...  764.  728.  758.]
  [ 987. 1080.  982. ...  775.  988. 1109.]
  [ 729.  821. 1020. ...  907.  902.  893.]]]
[[[ 104.    0.    0. ...  208.  208.  261.]
  [  52.    0.    0. ...  313.  313.  417.]
  [   0.    0.   52. ...  261.  470.  470.]
  ...
  [  52.  104.   52. ...    0.  104.   52.]
  

[[[ 52.  52.  52. ...   0.  52.  52.]
  [  0.  52.   0. ... 105. 210. 104.]
  [ 52. 156. 104. ...   0.  52.   0.]
  ...
  [208. 319. 522. ...  52.  52. 104.]
  [ 52. 208. 156. ...  52. 156.  52.]
  [ 52.   0.   0. ... 208.   0. 156.]]

 [[100.  99.  49. ...   0.  99. 249.]
  [  0.   0.   0. ... 299.  99. 100.]
  [  0.  99.  50. ... 199. 155.  99.]
  ...
  [  0.  49.   0. ...  50. 149. 299.]
  [ 49.   0.   0. ... 249.  99. 199.]
  [  0.   0.  49. ... 349.  99.   0.]]

 [[716. 685. 815. ... 734. 880. 728.]
  [594. 838. 831. ... 820. 597. 707.]
  [737. 740. 651. ... 942. 814. 738.]
  ...
  [712. 954. 897. ... 904. 709. 749.]
  [927. 752. 721. ... 783. 800. 963.]
  [864. 785. 669. ... 889. 767. 823.]]]
[[[ 156.  104.    0. ...    0.    0.    0.]
  [  52.    0.    0. ...    0.    0.    0.]
  [   0.    0.   52. ...    0.    0.    0.]
  ...
  [   0.    0.    0. ...   52.   52.   52.]
  [   0.    0.    0. ...  104.   52.   52.]
  [   0.    0.    0. ...  156.  208.    0.]]

 [[   0.    0.    0.

In [4]:
len(golgis)

132

In [5]:
for item in golgis:
    print(item.name + "\n" + item.group)

B4GALT1_unt_001_cell_1
B4GALT1
B4GALT1_unt_001_cell_2
B4GALT1
B4GALT1_unt_001_cell_3
B4GALT1
B4GALT1_unt_001_cell_4
B4GALT1
B4GALT1_unt_001_cell_5
B4GALT1
B4GALT1_unt_001_cell_6
B4GALT1
B4GALT1_unt_001_cell_7
B4GALT1
B4GALT1_unt_001_cell_8
B4GALT1
B4GALT1_unt_001_cell_9
B4GALT1
B4GALT1_unt_001_cell_10
B4GALT1
B4GALT1_unt_001_cell_11
B4GALT1
B4GALT1_unt_001_cell_12
B4GALT1
B4GALT1_unt_001_cell_13
B4GALT1
B4GALT1_unt_001_cell_14
B4GALT1
B4GALT1_unt_001_cell_15
B4GALT1
B4GALT1_unt_001_cell_16
B4GALT1
MGAT2_pH35_002_cell_1
pH3.5
MGAT2_pH35_002_cell_2
pH3.5
MGAT2_pH35_002_cell_3
pH3.5
MGAT2_pH35_002_cell_4
pH3.5
MGAT2_pH35_002_cell_5
pH3.5
MGAT2_pH35_002_cell_6
pH3.5
MGAT2_pH35_002_cell_7
pH3.5
MGAT2_pH35_002_cell_8
pH3.5
MGAT2_pH35_002_cell_9
pH3.5
MGAT2_pH35_002_cell_10
pH3.5
MGAT2_pH35_002_cell_11
pH3.5
MGAT2_pH35_002_cell_12
pH3.5
MGAT2_pH35_002_cell_13
pH3.5
MGAT2_pH40_003_cell_1
pH4.0
MGAT2_pH40_003_cell_2
pH4.0
MGAT2_pH40_003_cell_3
pH4.0
MGAT2_pH40_003_cell_4
pH4.0
MGAT2_pH40_003_ce

In [6]:
for item in golgis:
    item.calcRatio(0, 1)
    print(item.ratio)

1.3260400707839195
1.5260612922022379
1.2609334061107431
1.8062124162641704
1.5423162612448789
1.503555510793101
1.401871401771681
1.4180358058217057
1.4213001759645336
1.6068088517780186
1.1087991108029214
1.8999468269098312
1.7611558778376881
2.206691663609071
1.6123324602282094
1.4385485868260208
0.921279560868173
0.9179367924970783
0.9381400090331097
0.9787768336910966
0.8975989289241394
1.0365055770684177
1.041338679422923
1.05105767189082
1.0148268880963311
1.1858677575262078
1.0742911812330005
1.0735449156632388
1.0177975454840367
1.2778800610615317
1.3293020070974655
1.2834138695596398
1.201825046759515
1.405998709601133
1.2634580451091972
1.2999234805926714
1.080352814174721
1.388205415208417
0.5252525252525253
1.4680465968040954
0.9875166819769768
1.074517844952202
0.94382247498721
0.915871817235887
1.049769461763221
1.0802083250083587
1.0822590138025552
1.1122997016829421
1.0338975324267239
1.154835401234439
1.0226953487502135
1.0888277595344797
0.9492408284281696
1.13140840

In [7]:
golgis[0].toDataframe()

{'group': 'B4GALT1',
 'name': 'B4GALT1_unt_001_cell_1',
 'ratio': 1.3260400707839195}

In [17]:
group_set = set()
for item in golgis:
    group_set.add(item.group)

d = {}
for group in group_set:
    temp = []
    for item in golgis:
        if group == item.group:
            temp.append(item.ratio)
            d[group] = temp

{'B4GALT1': [1.3260400707839195,
  1.5260612922022379,
  1.2609334061107431,
  1.8062124162641704,
  1.5423162612448789,
  1.503555510793101,
  1.401871401771681,
  1.4180358058217057,
  1.4213001759645336,
  1.6068088517780186,
  1.1087991108029214,
  1.8999468269098312,
  1.7611558778376881,
  2.206691663609071,
  1.6123324602282094,
  1.4385485868260208],
 'MGAT2': [2.0643985790464043,
  2.5819971408275437,
  2.167377337048315,
  1.841208514473476,
  2.0535035993820925,
  1.9962395706511094,
  1.9762166878212057,
  2.182834280745744,
  2.166664240956831,
  2.938624486223996,
  2.2929582040417413],
 'pH3.5': [0.921279560868173,
  0.9179367924970783,
  0.9381400090331097,
  0.9787768336910966,
  0.8975989289241394,
  1.0365055770684177,
  1.041338679422923,
  1.05105767189082,
  1.0148268880963311,
  1.1858677575262078,
  1.0742911812330005,
  1.0735449156632388,
  1.0177975454840367],
 'pH4.0': [1.2778800610615317,
  1.3293020070974655,
  1.2834138695596398,
  1.201825046759515,
  1.

In [34]:
df = pd.DataFrame.from_dict(d, orient='index')

In [35]:
df = df.T

In [36]:
df

MGAT2     pH6.5     pH6.0     pH7.5     pH3.5     pH4.0     pH5.0  \
0   2.064399  1.834712  1.694891  2.339744  0.921280  1.277880  1.022695   
1   2.581997  1.858746  1.498800  2.467396  0.917937  1.329302  1.088828   
2   2.167377  1.881636  1.487731  2.774304  0.938140  1.283414  0.949241   
3   1.841209  1.938726  1.514724  2.416129  0.978777  1.201825  1.131408   
4   2.053504  1.575207  1.749122  2.961097  0.897599  1.405999  1.046790   
5   1.996240  1.664335  1.581385  2.651247  1.036506  1.263458  1.143550   
6   1.976217  1.967905  1.581664  2.535415  1.041339  1.299923  1.092825   
7   2.182834  1.943326  1.552861  2.912296  1.051058  1.080353  1.077757   
8   2.166664  2.019464  1.579165  2.658635  1.014827  1.388205  1.182234   
9   2.938624  2.049471  1.607211  2.948758  1.185868  0.525253  1.075962   
10  2.292958  2.508079  1.555430  2.811487  1.074291  1.468047       NaN   
11       NaN       NaN  1.559324  2.820106  1.073545       NaN       NaN   
12       NaN       NaN  1.620296  2.953394  1.017798       NaN       NaN   
13       NaN       NaN       NaN  2.905131       NaN       NaN       NaN   
14       NaN       NaN       NaN  2.753926       NaN       NaN       NaN   
15       NaN       NaN       NaN  2.540050       NaN       NaN       NaN   
16       NaN       NaN       NaN  3.316427       NaN       NaN       NaN   
17       NaN       NaN       NaN  3.210187       NaN       NaN       NaN   

     B4GALT1     pH5.5     pH7.0     pH4.5  
0   1.326040  1.071088  2.026721  0.987517  
1   1.526061  1.212500  2.598731  1.074518  
2   1.260933  1.462743  2.344886  0.943822  
3   1.806212  1.366970  2.614975  0.915872  
4   1.542316  1.276872  2.491914  1.049769  
5   1.503556  0.829958  2.245622  1.080208  
6   1.401871  1.693491       NaN  1.082259  
7   1.418036  1.589129       NaN  1.112300  
8   1.421300  1.552087       NaN  1.033898  
9   1.606809  1.395920       NaN  1.154835  
10  1.108799  1.862801       NaN       NaN  
11  1.899947  1.487923       NaN       NaN  
12  1.761156  1.408023       NaN       NaN  
13  2.206692       NaN       NaN       NaN  
14  1.612332       NaN       NaN       NaN  
15  1.438549       NaN       NaN       NaN  
16       NaN       NaN       NaN       NaN  
17       NaN       NaN       NaN       NaN

In [27]:
ph_cols = [col for col in df.columns if 'pH' in col]

In [28]:
ph_cols = [col for col in df.columns if 'pH' in col]
ph_df = df[ph_cols]

for i, col in enumerate(ph_cols):
    temp = col.split('pH')[1]
    ph_cols[i] = float(temp)

ph_df.columns = ph_cols

In [29]:
ph_df

6.5       6.0       7.5       3.5       4.0       5.0       5.5  \
0   1.834712  1.694891  2.339744  0.921280  1.277880  1.022695  1.071088   
1   1.858746  1.498800  2.467396  0.917937  1.329302  1.088828  1.212500   
2   1.881636  1.487731  2.774304  0.938140  1.283414  0.949241  1.462743   
3   1.938726  1.514724  2.416129  0.978777  1.201825  1.131408  1.366970   
4   1.575207  1.749122  2.961097  0.897599  1.405999  1.046790  1.276872   
5   1.664335  1.581385  2.651247  1.036506  1.263458  1.143550  0.829958   
6   1.967905  1.581664  2.535415  1.041339  1.299923  1.092825  1.693491   
7   1.943326  1.552861  2.912296  1.051058  1.080353  1.077757  1.589129   
8   2.019464  1.579165  2.658635  1.014827  1.388205  1.182234  1.552087   
9   2.049471  1.607211  2.948758  1.185868  0.525253  1.075962  1.395920   
10  2.508079  1.555430  2.811487  1.074291  1.468047       NaN  1.862801   
11       NaN  1.559324  2.820106  1.073545       NaN       NaN  1.487923   
12       NaN  1.620296  2.953394  1.017798       NaN       NaN  1.408023   
13       NaN       NaN  2.905131       NaN       NaN       NaN       NaN   
14       NaN       NaN  2.753926       NaN       NaN       NaN       NaN   
15       NaN       NaN  2.540050       NaN       NaN       NaN       NaN   
16       NaN       NaN  3.316427       NaN       NaN       NaN       NaN   
17       NaN       NaN  3.210187       NaN       NaN       NaN       NaN   

         7.0       4.5  
0   2.026721  0.987517  
1   2.598731  1.074518  
2   2.344886  0.943822  
3   2.614975  0.915872  
4   2.491914  1.049769  
5   2.245622  1.080208  
6        NaN  1.082259  
7        NaN  1.112300  
8        NaN  1.033898  
9        NaN  1.154835  
10       NaN       NaN  
11       NaN       NaN  
12       NaN       NaN  
13       NaN       NaN  
14       NaN       NaN  
15       NaN       NaN  
16       NaN       NaN  
17       NaN       NaN

In [31]:
pH_m = ph_df.melt(var_name="pH", value_name="Ratio")

In [32]:
pH_m

pH     Ratio
0    6.5  1.834712
1    6.5  1.858746
2    6.5  1.881636
3    6.5  1.938726
4    6.5  1.575207
5    6.5  1.664335
6    6.5  1.967905
7    6.5  1.943326
8    6.5  2.019464
9    6.5  2.049471
10   6.5  2.508079
11   6.5       NaN
12   6.5       NaN
13   6.5       NaN
14   6.5       NaN
15   6.5       NaN
16   6.5       NaN
17   6.5       NaN
18   6.0  1.694891
19   6.0  1.498800
20   6.0  1.487731
21   6.0  1.514724
22   6.0  1.749122
23   6.0  1.581385
24   6.0  1.581664
25   6.0  1.552861
26   6.0  1.579165
27   6.0  1.607211
28   6.0  1.555430
29   6.0  1.559324
..   ...       ...
132  7.0       NaN
133  7.0       NaN
134  7.0       NaN
135  7.0       NaN
136  7.0       NaN
137  7.0       NaN
138  7.0       NaN
139  7.0       NaN
140  7.0       NaN
141  7.0       NaN
142  7.0       NaN
143  7.0       NaN
144  4.5  0.987517
145  4.5  1.074518
146  4.5  0.943822
147  4.5  0.915872
148  4.5  1.049769
149  4.5  1.080208
150  4.5  1.082259
151  4.5  1.112300
152  4.5  1.033898
153  4.5  1.154835
154  4.5       NaN
155  4.5       NaN
156  4.5       NaN
157  4.5       NaN
158  4.5       NaN
159  4.5       NaN
160  4.5       NaN
161  4.5       NaN

[162 rows x 2 columns]